osx_image: xcode9
sudo: false
language: objective-c
podfile: Example/Podfile
before_script:
- cd Example && pod install && cd -
script:
- set -o pipefail && xcodebuild build test -workspace Example/WPMediaPicker.xcworkspace -scheme WPMediaPicker-Example -sdk iphonesimulator  -destination "name=iPhone 7" ONLY_ACTIVE_ARCH=NO | xcpretty -c
