osx_image: xcode9.2
language: objective-c
xcode_workspace: Aztec.xcworkspace
xcode_scheme: AztecExample
xcode_sdk: iphonesimulator
before_script:
- cd Example && carthage update && cd -
script:
- Scripts/build.sh
