version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0

commands:
  custom-carthage:
    steps:
      - run:
          name: Custom Carthage
          command: cd Example && ./carthage.sh build --platform iOS && cd ..
workflows:
  test_and_validate:
    jobs:
      - custom-carthage:
         steps:
           - custom-carthage

      - ios/test:
          name: Test
          xcode-version: "12.1.0"
          bundle-install: false
          pod-install: false
          workspace: Aztec.xcworkspace
          scheme: AztecExample
          device: iPhone 11
          ios-version: "13.0"

      - ios/validate-podspec:
          name: Validate WordPress-Aztec-iOS.podspec
          xcode-version: "12.1.0"
          podspec-path: WordPress-Aztec-iOS.podspec

      - ios/validate-podspec:
          name: Validate WordPress-Editor-iOS.podspec
          xcode-version: "12.1.0"
          podspec-path: WordPress-Editor-iOS.podspec
          # Reference WordPress-Aztec-iOS.podspec locally so we don't have to get it from the specs repo
          additional-parameters: --include-podspecs=WordPress-Aztec-iOS.podspec

      - ios/publish-podspec:
          name: Publish WordPress-Aztec-iOS to Trunk
          xcode-version: "12.1.0"
          podspec-path: WordPress-Aztec-iOS.podspec
          post-to-slack: true
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

      - ios/publish-podspec:
          name: Publish WordPress-Editor-iOS to Trunk
          requires: [ "Publish WordPress-Aztec-iOS to Trunk" ]
          xcode-version: "12.1.0"
          podspec-path: WordPress-Editor-iOS.podspec
          post-to-slack: true
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
