version: 2.1

orbs:
  # This uses the iOS Orb located at https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@0.0.24

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Test
          carthage-update: true
          carthage-working-directory: Example
          bundle-install: false
          pod-install: false
          workspace: Aztec.xcworkspace
          scheme: AztecExample
          device: iPhone XS
          ios-version: "12.1"

      - ios/validate-podspec:
          name: Validate WordPress-Aztec-iOS.podspec
          podspec-path: WordPress-Aztec-iOS.podspec

      - ios/validate-podspec:
          name: Validate WordPress-Editor-iOS.podspec
          podspec-path: WordPress-Editor-iOS.podspec
          # Updating specs is needed since WordPress-Editor-iOS depends on WordPress-Aztec-iOS
          update-specs-repo: true
